plugins:
  - "@dotcom-tool-kit/component"
  - "@dotcom-tool-kit/webpack"
  - "@dotcom-tool-kit/jest"
hooks:
  test:local:
    - JestLocal
  build:local:
    - WebpackDevelopment
options:
  "@dotcom-tool-kit/circleci":
    nodeVersion:
      - '18.17'
      - '16.20'
  "@dotcom-tool-kit/webpack":
    configPath: "./webpack.config.js"
